# Generated by Django 4.1.4 on 2022-12-14 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRModel',
        ),
    ]
