# Generated by Django 4.1.4 on 2022-12-14 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrmodel',
            name='url',
        ),
    ]
