# Generated by Django 4.1.4 on 2022-12-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodeapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QRModel',
        ),
    ]
