# Generated by Django 4.1.4 on 2022-12-14 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodeapp', '0004_alter_qrmodel_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrmodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
