# Generated by Django 4.1.4 on 2022-12-14 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qrcodeapp', '0005_rename_user_id_qrmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
