# Generated by Django 4.1.4 on 2022-12-14 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodeapp', '0006_alter_qrmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrmodel',
            name='user',
        ),
    ]
