# Generated by Django 4.1.4 on 2022-12-14 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcodeapp', '0007_remove_qrmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrmodel',
            name='url',
            field=models.URLField(),
        ),
    ]
